### ISSUE TITLE
Subroutes don't mark navlink active

### ISSUE THREAD

**Issue by coderenaissance** [yahoo/fluxible-router#109]
With the routes below implemented,  the user clicks on a header navlink to go to the user dashboard (The link is title "Users") and that link is marked as active. The daskboard lists users and allows a specific user can be clicked on which will redirect to the User view/route/component. 

The problem is that the header navlink "Users" is no longer active(which makes sense because it doesn't match the current url and you don't support sub-routes). Other than doing something hacky like having the User component make a jquery call to set a css class on the navlink(anchor), is there a way to make the users NavLink highlight? 

users: {
    method: 'get',
    path: resolveRoute('/users'),
    handler: UserDashboard
  }
 user: {
    method: 'get',
    path: resolveRoute('/users/:id'),
    handler: User
  },

**Comment by mridgway** [comment]
fluxible-router does not have a concept of route nesting like react-router does at this time. You would have to manage active states on your own by passing in an active prop for this to work I think.
