### ISSUE TITLE
Disabling scrollTop functionality between navigations

### ISSUE THREAD

**Issue by nitoo7** [yahoo/fluxible-router#113]
Hi,

I would like to set 'enableScroll' in handleHistory to false so that scroll position is maintained. Could someone tell me how i could do that?

**Comment by lingyan** [comment]
hi @nitoo7 I just updated the example code snippet in API doc to show how to do that: https://github.com/yahoo/fluxible/blob/master/packages/fluxible-router/docs/api/handleHistory.md#example-usage

Let me know if any more questions.  Thanks!

**Comment by nitoo7** [comment]
Thanks a lot. It worked :)

**Comment by lingyan** [comment]
Glad to hear! 👍
