### ISSUE TITLE
How to redirect properly?

### ISSUE THREAD

**Issue by longlho** [yahoo/fluxible-router#15]
Hi guys,

How do I redirect properly with this library? By *properly* I mean on the server side, it'll result in a `301`/`302` status code and on the client side, it'll `replaceState` and renders the new view.

Thanks!

**Comment by jedireza** [comment]
In your `/server.js` file you typically execute the `navigateAction` to kick things off. One way to accomplish the redirect would be to return an error from your route action and add `statusCode` and `redirectUrl` properties to the error object. You could check for these and use them like:

```js
server.use(function (req, res, next) {
    const context = app.createContext({
        req: req, // The fetchr plugin depends on this
        xhrContext: {
            _csrf: req.csrfToken() // Make sure all XHR requests have the CSRF token
        }
    });

    context.executeAction(navigateAction, { url: req.url }, function (err) {
        if (err) {
            if (err.statusCode === 301) {
                res.redirect(err.redirectUrl);
            }
            else {
                // handle error in another way
            }
        }
        else {
            // render the app like usual
        }
    });
});
```

Thoughts on this approach @mridgway @redonkulus?

**Comment by mridgway** [comment]
Yes, this is probably how I would do it as well. You can also store the redirect status code and url in a store and access it from the middleware.

**Comment by nathanwelch** [comment]
We put this into a Fluxible plugin that adds a `redirectTo` and a `hasRedirected` function to the action context. When we handle the request on the server, we pass in the Express response so our plugin can have access to it. Then we can know not to render if `context.getActionContext().hasRedirected()`. Not sure if putting things on the actionContext like this is how plugins were intended to be used, but we liked this more than using err.

Here's the relevant parts of our our server.use(): 
```
server.use(function (req, res, next) {
	var context = app.createContext({
		req: req,
		// Pass Express res for redirector plugin
		res: res
	});

	context.executeAction(navigateAction, {
		url: req.url
	}, function (err) {
		// Actual error
		if (err) {
			next(err);
			return;
		} else if (context.getActionContext().hasRedirected()) {
			return;
		}

		// Just the standard React.renderToStaticMarkup in a common function so our error middleware can use it too
		var html = RenderUtils.getPageHtml(context, app, config, appEnv);
		res.send(html);
	});
});
```

Our full plugin has a little more logic than this but here's the bulk of it. You should be able to use a navigateAction on the client or a NavLink to do the replaceState stuff. That could be added to the plugin as well so you don't have to care about where you are when you call `redirectTo`. 

```
{
	name: 'RedirectorPlugin',

	plugContext: function (options) {
		var expressResponse = options.res;

		return {
			plugActionContext: function (actionContext) {
				actionContext.redirectTo = function (url, redirectOptions) {
					if (!expressResponse || (!url && url !== '')) {
						return;
					}

					// Make sure the URL starts with a / so it isn't interpreted as a relative URL
					if (url.substring(0, 1) !== '/') {
						url = '/' + url;
					}

					redirectOptions = redirectOptions || {};
					var status = redirectOptions.status || 303;

					expressResponse.redirect(status, url);
					this.redirectedTo = url;
				};

				actionContext.hasRedirected = function () {
					return !!this.redirectedTo;
				};
			}
		};
	}
}
```
