### ISSUE TITLE
Feature Request - Handle onbeforeunload

### ISSUE THREAD

**Issue by gfranko** [yahoo/fluxible-router#16]
We need to handle the situation when a user leaves a particular page and the `window.onbeforeunload()` method does not seem to be called with the router.

A possible solution would be to patch [navigateAction.js](https://github.com/yahoo/fluxible-router/blob/master/lib/navigateAction.js) to check if there is a `window.onbeforeunload()` method defined on the `window`, retrieve the string value from it, and then call `window.confirm()` with the appropriate string.

Thoughts?

**Comment by redonkulus** [comment]
This was fixed by #19
