### ISSUE TITLE
CHANGE_ROUTE_* deprecated

### ISSUE THREAD

**Issue by mjurczyk** [yahoo/fluxible-router#26]
Docs:
https://github.com/yahoo/fluxible-router/blob/master/docs/api/navigateAction.md
https://github.com/yahoo/fluxible-router/blob/master/docs/api/NavLink.md

Are obviously out of sync compared to the actual source:
https://github.com/yahoo/fluxible-router/blob/master/lib/navigateAction.js

`CHANGE_ROUTE_*` doesn't seem to be there anymore, update to `NAVIGATE_*`?

**Comment by mridgway** [comment]
Fixed in https://github.com/yahoo/fluxible-router/pull/27/files
