### ISSUE TITLE
Undefined variable in handleHistory.js

### ISSUE THREAD

**Issue by phuson** [yahoo/fluxible-router#29]
On this line:

https://github.com/yahoo/fluxible-router/blob/master/lib/handleHistory.js#L109

`this._enableScroll` appears to be undefined. Is this a typo?

**Comment by Vijar** [comment]
@phuson looks like this is a relic from when we repurposed the old [RouterMixin](https://github.com/yahoo/flux-router-component/blob/master/lib/RouterMixin.js) into `handleHistory`.

This is indeed a bug and we need to change all instances of `this._enableScroll` to `options.enableScroll`. Would you like to submit a PR?

**Comment by phuson** [comment]
@Vijar Sure, I'll submit a PR for this soon.

**Comment by mridgway** [comment]
Fixed by #34.
