### ISSUE TITLE
Moving to Immutable Objects

### ISSUE THREAD

**Issue by sAbakumoff** [yahoo/fluxible-router#36]
Hello,
The upgrade guide at https://github.com/yahoo/fluxible-router/blob/master/UPGRADE.md is the great document and it helped me a lot on upgrading to the recent fluxible.
However, it can improved further with the list of all the objects that became immutable. I.e. I found that the parameters passed in action function of the route are now immutable and instead of using something like
```javascript
    customer :{
        method : 'get',
        path : '/customer/:id',
        page : pages.customer,
        action : function(context, payload, done){
          context.executeAction(getCustomerDetails, {filters : payload.params}, done);
        }
    }
```
I now have to use
```javascript
filters : payload.get('params')
```
Thanks!

**Comment by mridgway** [comment]
Will make a not of this in the guide. Thanks!

**Comment by mridgway** [comment]
Added in https://github.com/yahoo/fluxible-router/commit/d300795ab8a3950b511df9898b22f24298caeb00
