### ISSUE TITLE
fluxible should be a peer dependency

### ISSUE THREAD

**Issue by lo1tuma** [yahoo/fluxible-router#40]
Currently `fluxible` is a normal dependency of `fluxible-router`. As you can see in the [flux-examples](https://github.com/yahoo/flux-examples/blob/0683e7b4ea70b6e504ce0bdd83c40a0d44daca54/package.json#L16-L18) this can be problem causing two different versions of fluxible in your bundled javascript file.

**Comment by mridgway** [comment]
Typically npm will hoist the dependency if the versions are the same and only install in the root folder that has the `fluxible` dependency. Are you seeing it installed twice somewhere?

**Comment by lo1tuma** [comment]
The problem with that is that you always have to know which version of fluxible is used by fluxible-router and keep them in sync. Using a peerDependency would show you warning during `npm install` if the version doesn’t match with the version defined in fluxible-router.

In my case I always use exact version numbers in my package.json, so if I depend on fluxible `0.4.8` and fluxible-router depends on `^0.4.9` I will end up with two versions of fluxible.

**Comment by mridgway** [comment]
Fair point about the warning. We will make that change.

**Comment by lo1tuma** [comment]
Awesome, thanks :+1:.

**Comment by mridgway** [comment]
Changed in v0.1.8.
