### ISSUE TITLE
Animations

### ISSUE THREAD

**Issue by Dharmoslap** [yahoo/fluxible-router#43]
There should be some convenient way how to create animations before and after route transition.

**Comment by gpbl** [comment]
An way could be `React.addons.CSSTransitionGroup`. In your root component (where you are rendering the route handler), make sure you give an unique key to the handler:

```jsx
render() {
  return (
    <ReactCSSTransitionGroup transitionName="myTransition">
       <Handler key={currentRoute.get("url")} />
    </ReactCSSTransitionGroup>
  );
}
```
