### ISSUE TITLE
Detect automatically when to follow a link

### ISSUE THREAD

**Issue by lo1tuma** [yahoo/fluxible-router#44]
It would be a nice addition to `NavLink` if it would be possible to detect automatically if the link should be followed or if the the `navigateAction` should be executed.

One way to do this, would be to check if the current `href` matches any defined route, if not the link should be followed.

**Comment by anotherthomas** [comment]
One usecase (which we actually have) would be that you render links based on data from a CMS. 
In the code we cannot be sure whether the content is a route within the site or to external content.

**Comment by mridgway** [comment]
This sounds reasonable to me. :+1:
