### ISSUE TITLE
unicode url not working correctly for the Navlink

### ISSUE THREAD

**Issue by ssmlee04** [yahoo/fluxible-router#48]
When the `Navlink` is dealing with unicode urls it will not work correctly. My guess is it doesn't encode the url before sending out the ajax calls. So the API server or the backend will not see the correct url.

Currently I do 
`href = encodeURI(href)`
inside the `dispatchNavAction` function. But I am not sure if this is a temp solution or is it correct. Could you guys take a look at it? Thanks.

**Comment by mridgway** [comment]
Hmm, are you sure this is a router problem or does this have to do with fluxible-plugin-fetchr? Fluxible router does not do AJAX, but it does call `history.pushState`. Maybe the issue is there. I will see if I can reproduce an issue with routes have unicode.

**Comment by ssmlee04** [comment]
not really sure.  But without the one line code `href = encodeURI(href)` I will see when I click on the `Navlink` the website is calling the backend API server with weird routes the API server cannot read.

**Comment by gpbl** [comment]
I tried in my app and i have no issues with unicode. I suspect it's something in @ssmlee04 backend API not parsing unicode when receiving XMLHttpRequest calls.

**Comment by ssmlee04** [comment]
Currently I kind of put all the links that involves Unicode characters with `href = encodeURI(href);`  

I tried to make API calls to the backend API server using both Postman and links from Navlinks. 

The test link that contains the unicode characters are: 
https://localhost:8000/places/777咖啡-taiwan-taipeicity-556e76e00cfaa9fe78080b7a

those characters are Chinese btw. 

the request sent using Postman looks like this on the backend. Response status is 200.

![](http://i.stack.imgur.com/rLQGz.png)

the request from Navlink doing `href = encodeURI(href)` also give the same result.  

But if I don't do it the request would look like this

![](http://i.stack.imgur.com/l6wTX.png)

the response status is 500. Express even failed to parse the route correctly

Because when I paste the same route into Postman and from Navlink the behavior on the backend is different. This is why I think the problem isn't from the backend?
