### ISSUE TITLE
Payload passed to route action is an Immutable object

### ISSUE THREAD

**Issue by gpbl** [yahoo/fluxible-router#5]
It seems my route actions are getting the whole route (an Immutable object) as payload: is that expected or am I doing something wrong? i was expecting a plain object.

I believe the line passing the route payload is this one:
https://github.com/yahoo/fluxible-router/blob/master/lib/navigateAction.js#L42

**Comment by mridgway** [comment]
So this was by design, but we could re-evaluate it. I wasn't a fan of incurring the cost of converting back to a raw object for passing it as a payload, but that may make more sense.

**Comment by gpbl** [comment]
Ah nice :+1: for Immutable: the docs don't even mention it – hence my surprise. I do agree it makes sense to work always with the same objects, however it is a design detail that should be clearly stated.

**Comment by jedireza** [comment]
I added a mention about this in the upgrade guide but maybe it should be added somewhere else. Ideas are welcome.

**Comment by coffeedeveloper** [comment]
In my project. I find something like bug.
```
<NavLink routeName="topic" navParams={{id: 1}}> lol </NavLink>
```
Then in `Topic` component use the `currentNavigate` can get the `params` but refresh the page, `params` will be `undefined`.

At first I thought it was a bug, but then I look at the source code. Found in `currentRoute`.

so now i can only use `currentRoute` in component.

```
var params = this.context.getStore(RouteStore).getCurrentStore().toJS().params;
```

But this is not intuitive.

**Comment by mridgway** [comment]
Added more to the upgrade guide about this.
