### ISSUE TITLE
Multilanguage support

### ISSUE THREAD

**Issue by olegman** [yahoo/fluxible-router#50]
I'm building multilingual site where the language preference is part of the URL, e.g.
```
http://example.com/<somepage>      (Russian, default)
http://example.com/en/<somepage>   (English)
http://example.com/jp/<somepage>   (Japanese)
http://example.com/../             (etc)
```
Everything is ok, when I use prefix for all languages:
```
path: '/:lang/<somepage>'
```
But for default language, I don't need to include language in url, as shown in example. Any ideas how to handle this use case?

**Comment by redonkulus** [comment]
Seems like that would just be another route that is before the one's that specify the lang. Then your action can specify a default language for that route.

```js
module.exports = {
    page: {
        method: 'GET',
        path: '/:page',
        handler: require('../components/Page.jsx'),
        // Executed on route match
        action: require('../actions/loadPage')
    },
    pageLang: {
        method: 'GET',
        path: '/:lang/:page',
        handler: require('../components/Page.jsx'),
        action: require('../actions/loadPage')
    }
};
```

Then in your loadPage action, you can specify a default lang if one is not part of the route.

Alternatively, you could just have one route that uses a regex to check for lang:

```js
{
    page: {
        method: 'GET',
        path: '(/:lang)?/:page',
        handler: require('../components/Page.jsx'),
        action: require('../actions/loadPage')
    }
}
```

**Comment by olegman** [comment]
Thanks for reply! This seems work fine for me:
```
path: '/:lang([a-z]{2})?/<somepage>'
```

**Comment by maiopirata** [comment]
I'm trying also to get some help here:
https://github.com/gpbl/isomorphic500/issues/87

I have a sligthly different problem. I want to change the url name also!

    http://example.com/<somepage url in russian>      (Russian, default)
    http://example.com/en/<somepage url in english>   (English)
    http://example.com/jp/<somepage url in japanese>   (Japanese)
    http://example.com/../             (etc)

We can eventually create 4 different routes that point to the same handler, but I would like to use also google hreflang metatag to link the pages in different languages.
