### ISSUE TITLE
Required context `getStore` was not specified in `RouteHandlerStoreConnector`.'

### ISSUE THREAD

**Issue by mmahalwy** [yahoo/fluxible-router#53]
Getting error:
```
WARN: 'Warning: Failed Context Types: Required context `getStore` was not specified in `RouteHandlerStoreConnector`.'
```

When testing a component wrapped in `handleRoute()`

How can I get by this? 

Thanks!

**Comment by mridgway** [comment]
This is most likely a `owner` vs `parent` context issue. Are you using react-router? Also, how are you wrapping your app level component to provide it context?

**Comment by mmahalwy** [comment]
No I am using fluxible-router with my component wrapped in `handleRoute`

The solution was to do `provideContext` in my tests...
