### ISSUE TITLE
How to deal with nested routes with this module?

### ISSUE THREAD

**Issue by x1a0** [yahoo/fluxible-router#55]
Hi,

Let's say I have 2 components:

- `Account`, route path: `/account`
- `BillingHistory`, route path: `/account/billing`

When user goes to account page, `loadUser` action is triggered and user data will be stored in `UserStore`.
When user goes to billing history page, `loadBillingHistory` action is triggered and billing history data will be stored in `BillingStore`.
While in billing history page, the component may also need to access `UserStore` to load some user information.

Is there a way to put billing history route as a child of account route, so all required actions can be triggered in the route tree - instead of repeat calling same actions in each route?

**Comment by mridgway** [comment]
fluxible-router does not currently support nested routes like react-router does. You would have to call multiple actions from a wrapper action. Ideally, you can check your store whether it has the information it needs before firing service calls so that you aren't refetching the same data.
