### ISSUE TITLE
current route query object is empty even when query params exist

### ISSUE THREAD

**Issue by mailaneel** [yahoo/fluxible-router#65]
Using ```HistoryWithHash``` with below configuration

```js
new HistoryWithHash({
            useHashRoute: true,
            defaultHashRoute: '/comments'
  }
```

Example route config

```js
var routesConfig = {
      comments: '/comments'
}
```

Assuming user visits  any one of below urls
* ```http://example.com/?user=test```, 
* ```http://example.com/?user=test#/comments```

### expected current route
```js
{
 "name": "comments",
 "url": "/comments",
 "params": {},
 "query" : {
    "user": "test"
   },
   "navigate": {} // ignore this for now
}
```

### current result

```js
{
 "name": "comments",
 "url": "/comments",
 "params": {},
 "query" : {},
  "navigate": {} // ignore this for now
}
```

I am expecting every query param from the url to be available for me in current route object 

Possible problem in this line [RouteStore:75](https://github.com/yahoo/fluxible-router/blob/master/lib/RouteStore.js#L75) ?

**Comment by mailaneel** [comment]
on further investigation, this is how ```HistoryWithHash``` is implemented
[HistoryWithHash:109](https://github.com/yahoo/fluxible-router/blob/master/addons/HistoryWithHash.js#L109)

* ```http://example.com/#/comments?user=test``` works i.e query object will have user key
* ```http://example.com/?user=test#/comments``` do not work i.e query object will not have user key


Example of how angular [router](http://plnkr.co/edit/?p=preview) works

**Comment by mridgway** [comment]
I think this is by design and usually how hash based history is done. The query param that is before the hash would only be used by the server. The issue is that if you change the query param as in your example, you would be going back to the server for the document.
