### ISSUE TITLE
history state pushed twice

### ISSUE THREAD

**Issue by pumpikano** [yahoo/fluxible-router#66]
I am experiencing an issue where the history state is pushed twice in a single route when calling `navigateAction`. `RouteStore` handles both `NAVIGATE_START` and `NAVIGATE_SUCCESS` events by updating the store and calling `emitChange`. Since `handleHistory` listens to `RouteStore`, it's `componentDidUpdate` method ends up being called twice, once for each of those two events. There are no checks in `componentDidUpdate` to prevent the history state from being pushed twice.

Am I somehow misusing something here?

My proposed fix is to only push the history state when the navigation is complete and succeeds, probably by checking `this.props.isNavigateComplete` and `this.props.currentNavigateError` in `componentDidUpdate`. Does this sound like a reasonable strategy? I should note that many of `handleHistory`'s tests will need to change since many of the tests test state after `routeStore._handleNavigateStart` is called.

**Comment by mridgway** [comment]
We do check the url to see if it is the same before we call pushState/replaceState here: https://github.com/yahoo/fluxible-router/blob/master/lib/handleHistory.js#L158

Can you check to see why this check is not working for you?

The history change is expected to change immediately and not on completion of the action. The idea is that this is the same behavior that you get when you do a full HTTP load of a page: the url changes and then the actually HTTP call happens.

**Comment by pumpikano** [comment]
Ah, yes you are right - I missed that logic before. The behavior makes sense. In my case, `nav.url` was not url encoded and `getUrl()` was returning an encoded version during the second call.

Thanks for the help.
