### ISSUE TITLE
each navigateAction call increases history length by 2, stuffs up browser back button?

### ISSUE THREAD

**Issue by mailaneel** [yahoo/fluxible-router#67]
Every navigateAction calls [```handleHistory:componentDidUpdate```](https://github.com/yahoo/fluxible-router/blob/master/lib/handleHistory.js#L146) twice

first for ``` NAVIGATE_START```
second for  ```NAVIGATE_SUCCESS```

Back button is not working properly because of this.

**Comment by mridgway** [comment]
Hi @mailaneel, could you look at https://github.com/yahoo/fluxible-router/issues/66 and see if this is the same issue you are seeing?

**Comment by mailaneel** [comment]
@mridgway thanks same issue.

I am using transform on route to solve https://github.com/yahoo/fluxible-router/issues/65 which returns transformed url.

So when we compare they are do not match. Any Suggestions 

Transform: /?q=test#comments => /comments?q=test

**Comment by mailaneel** [comment]
My bad works fine now, I am doing it in reverse instead of transform
thanks once again @mridgway
