### ISSUE TITLE
SyntaxError: Expected "\\#", "\\u", "\\{", "\\}", "{", [^{}\\\0-\x1F \t\n\r], end of input or whitespace but "\\" found.

### ISSUE THREAD

**Issue by geekyme** [yahoo/fluxible-router#71]
When a user navigates to a route with query parameter ending with a backslash \, the above syntax error will be thrown. 

eg. `/search?query=test\` will throw the error.

This will happen both on the front end and backend on an isomorphic app where routes are shared. It appears that it is happening on the navigateAction call.

**Comment by mridgway** [comment]
@lingyan Could this be happening within routr?

**Comment by lingyan** [comment]
routr strips off query string and hash before trying to match a url to routes: https://github.com/yahoo/routr/blob/master/lib/router.js#L74-L94

@geekyme Does the stack trace show which lib/line throws the error?

**Comment by geekyme** [comment]
Unfortunately no, there was no stack trace. :(

**Comment by geekyme** [comment]
Following up on this, got the same syntax error triggering when a user access the route with query parameter `?query=%5BD.Y.O.N%5DPopular+Taiwan+Teeth+Whitening+Spa%21%7B+`

**Comment by jithin1987** [comment]
This error actually comes from https://github.com/yahoo/intl-messageformat when there is escaped '\'
