### ISSUE TITLE
NavLink activeClass not triggering on server render

### ISSUE THREAD

**Issue by albertorestifo** [yahoo/fluxible-router#77]
I have a `NavLink` element inside the header element:

```html
<NavLink href='/occ/' activeClass='active'>Hub</ NavLink>
```

On the render from the server, the class is not applied to the anchor tag. If clicked on the client, however it is immediately applied.

Demo GIF:
![bug](https://cloud.githubusercontent.com/assets/1037048/9225717/2dd081f2-410b-11e5-8d75-deb447b4ef76.gif)

What might the cause be? I can post more code if required, but I'm not sure what's relevant.

**Comment by redonkulus** [comment]
The active state is based on the URL of the NavLink component and the current URL of the page. Your activeClass code will not be used, if the link is not active. You can see the code here: https://github.com/yahoo/fluxible-router/blob/master/lib/createNavLinkComponent.js#L74

Here is the store code: https://github.com/yahoo/fluxible-router/blob/master/lib/RouteStore.js#L113

**Comment by albertorestifo** [comment]
@redonkulus Thanks for the input, it was really helpful in diagnosing my code.

For reference, I found the issue:

On the server, using express, I was triggering the `executeAction` method passing as `url` parameter the result of `req.baseUrl`, seems fine at first sight except that when navigating to `/example/`, the resulting Express `baseUrl` is `/example`.

That explains why there was no change in url when clicking the anchor, but only in styling.
