### ISSUE TITLE
Client only setup with navigateAction?

### ISSUE THREAD

**Issue by edword** [yahoo/fluxible-router#83]
Hi, wondering if there are any client.js examples floating around for a client-only setup (i.e. no corresponding server.js or rehydrate/dehydratedState handling in client.js) with navigateAction?

Thx!

**Comment by redonkulus** [comment]
@edword take a look at our `flux-examples` chat example, we provide query params that show you how it would work if deferred the data loading and rendering to the client:
https://github.com/yahoo/flux-examples/tree/master/chat#usage
