### ISSUE TITLE
currentNavigate is not immutable

### ISSUE THREAD

**Issue by tonykung06** [yahoo/fluxible-router#84]
it seems currentRoute is immutable while currentNavigate is not, so when it is used with immutablecontainer, it gives a corresponding warning.

**Comment by mridgway** [comment]
`currentNavigate` is regenerated every time, so while it is not an immutable.js object, it is actually immutable. I don't know that it's worth the overhead to make this object an immutable.js object every time. 

Which immutablecontainer are you using that throws this error?

**Comment by tonykung06** [comment]
I am using fluxible-immutable-utils/lib/createImmutableContainer in this way

class Container extends React.Component { ... }
Container = createImmutableContainer(Container, { 
    getStateFromStores: (context, props) => {
      //using props.currentRoute here
    }
 });

Container = handleRoute(Container);

**Comment by koulmomo** [comment]
it's undocumented, but you can pass an [`ignore` option](https://github.com/yahoo/fluxible-immutable-utils/blob/183bce6fd5678fa0d44c3609235e0a5a9fb7abf3/lib/createImmutableContainer.js#L30) to have the immutable container ignore certain props.

so:

```
class Container extends React.Component { ... }
Container = createImmutableContainer(Container, { 
    getStateFromStores: (context, props) => {
      //using props.currentRoute here
    },

   ignore: ['currentNavigate']
 });

Container = handleRoute(Container);
```

**Comment by mridgway** [comment]
Closing this since there is a workaround for use with the immutable utils. I think in the future we may rethink whether we should have immutable.js in the core library. It may make more sense for us to use reducers in the RouteStore and use raw immutable objects instead.

**Comment by localnerve** [comment]
+1 for remove immutable.js from core lib. Much savings.

**Comment by gpbl** [comment]
Me too, I'm for RouteStore using reducers.
