### ISSUE TITLE
Pattern for waiting for server data to load?

### ISSUE THREAD

**Issue by agrippanux** [yahoo/fluxible-router#9]
With fluxible-router-component, a route component delays rendering until the done() of an action is complete.

fluxible-router switches the route as soon as NAVIGATE_START is called and the RouteStore isn't listening for NAVIGATE_SUCCESS.  What's the desired pattern to delay loading the component until server data returns?

**Comment by mridgway** [comment]
There isn't a way right now other than to use your own `RouteStore` or extending the built-in one. This could be an enhancement to the current `RouteStore` though: maintaining pending route change state.

**Comment by jedireza** [comment]
Now we have a `isNavigateComplete` property that is passed when `NAVIGATE_SUCCESS` or `NAVIGATE_FAILURE` is heard. We'll be using this in our fluxible.io site. You can see the example usage here: https://github.com/yahoo/fluxible.io/pull/120/files?diff=unified#diff-e7d9b2441bd9e93366aca6ba7a5eccdeR21

**Comment by agrippanux** [comment]
this is terrific, thanks - just upgraded and everything is working fine
