### ISSUE TITLE
Remove dependency on Immutable.js

### ISSUE THREAD

**Issue by mridgway** [yahoo/fluxible-router#98]
Instead of pulling in the full library, we should use plain objects that are created anew for each navigation rather than mutating existing objects.

**Comment by irae** [comment]
Immutable is approximately, before Gzip, 64.52% of the router size.

![screenshot 2015-11-06 at 6 43 16 pm](https://cloud.githubusercontent.com/assets/98254/11013174/0829ef52-84b7-11e5-9aa9-02477224fb78.PNG)

[HTML here](https://gist.github.com/irae/81e9782bcbe3497a8a73) -- generated with [disc](https://github.com/hughsk/disc)

**Comment by irae** [comment]
Needs package version bump and `npm publish` so everyone can get the size reduction.
